import Head from 'next/head'
import { useState } from 'react'
import { RandomFox } from './components/RandomFox'

interface ImageItem {
  id: number
  url: string
}

const random = (): number => Math.floor(Math.random() * 123) + 1

export default function Home (): JSX.Element {
  const [images, setImages] = useState<ImageItem[]>([
    { id: 1, url: `https://randomfox.ca/images/${random()}.jpg` },
    { id: 1, url: `https://randomfox.ca/images/${random()}.jpg` },
    { id: 1, url: `https://randomfox.ca/images/${random()}.jpg` },
    { id: 1, url: `https://randomfox.ca/images/${random()}.jpg` }
  ])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        {images.map(({ id, url }) => <RandomFox key={id} srcImage={url}/>)}
      </main>
    </>
  )
}
