import { type NextPage } from 'next'
import { type MouseEventHandler } from 'react'
import { useState } from 'react'
import Head from 'next/head'
import { RandomFox } from './components/RandomFox'

interface ImageItem {
  id: string
  url: string
}

const generateId = (): string => Math.random().toString(36).substring(2, 9)

const random = (): number => Math.floor(Math.random() * 123) + 1

const Home: NextPage = () => {
  const [images, setImages] = useState<ImageItem[]>([])

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (event): void => {
    event.preventDefault()
    const newFoxItem: ImageItem = {
      id: generateId(),
      url: `https://randomfox.ca/images/${random()}.jpg`
    }
    setImages([
      ...images,
      newFoxItem
    ])
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1>Holi  </h1>
        <button onClick={addNewFox}>Add new fox</button>
        {images.map(({ id, url }) => <RandomFox key={id} srcImage={url}/>)}
      </main>
    </>
  )
}
export default Home
